namespace Spdx;

public sealed partial class SpdxLicense
{
    internal static IReadOnlyList<SpdxLicense> GenerateLicenseList()
    {
        return new List<SpdxLicense>
        {
            new SpdxLicense("EUDatagrid", "EU DataGrid Software License", "https://spdx.org/licenses/EUDatagrid.html", "https://spdx.org/licenses/EUDatagrid.json",true, true, false),
            new SpdxLicense("VOSTROM", "VOSTROM Public License for Open Source", "https://spdx.org/licenses/VOSTROM.html", "https://spdx.org/licenses/VOSTROM.json",false, false, false),
            new SpdxLicense("GFDL-1.3-no-invariants-only", "GNU Free Documentation License v1.3 only - no invariants", "https://spdx.org/licenses/GFDL-1.3-no-invariants-only.html", "https://spdx.org/licenses/GFDL-1.3-no-invariants-only.json",false, false, false),
            new SpdxLicense("CC-BY-SA-1.0", "Creative Commons Attribution Share Alike 1.0 Generic", "https://spdx.org/licenses/CC-BY-SA-1.0.html", "https://spdx.org/licenses/CC-BY-SA-1.0.json",false, false, false),
            new SpdxLicense("CC-BY-3.0-DE", "Creative Commons Attribution 3.0 Germany", "https://spdx.org/licenses/CC-BY-3.0-DE.html", "https://spdx.org/licenses/CC-BY-3.0-DE.json",false, false, false),
            new SpdxLicense("CC-BY-SA-2.5", "Creative Commons Attribution Share Alike 2.5 Generic", "https://spdx.org/licenses/CC-BY-SA-2.5.html", "https://spdx.org/licenses/CC-BY-SA-2.5.json",false, false, false),
            new SpdxLicense("HaskellReport", "Haskell Language Report License", "https://spdx.org/licenses/HaskellReport.html", "https://spdx.org/licenses/HaskellReport.json",false, false, false),
            new SpdxLicense("SimPL-2.0", "Simple Public License 2.0", "https://spdx.org/licenses/SimPL-2.0.html", "https://spdx.org/licenses/SimPL-2.0.json",true, false, false),
            new SpdxLicense("ClArtistic", "Clarified Artistic License", "https://spdx.org/licenses/ClArtistic.html", "https://spdx.org/licenses/ClArtistic.json",false, true, false),
            new SpdxLicense("Nunit", "Nunit License", "https://spdx.org/licenses/Nunit.html", "https://spdx.org/licenses/Nunit.json",false, true, true),
            new SpdxLicense("SMPPL", "Secure Messaging Protocol Public License", "https://spdx.org/licenses/SMPPL.html", "https://spdx.org/licenses/SMPPL.json",false, false, false),
            new SpdxLicense("LGPL-2.0+", "GNU Library General Public License v2 or later", "https://spdx.org/licenses/LGPL-2.0+.html", "https://spdx.org/licenses/LGPL-2.0+.json",true, false, true),
            new SpdxLicense("CUA-OPL-1.0", "CUA Office Public License v1.0", "https://spdx.org/licenses/CUA-OPL-1.0.html", "https://spdx.org/licenses/CUA-OPL-1.0.json",true, false, false),
            new SpdxLicense("OLDAP-1.3", "Open LDAP Public License v1.3", "https://spdx.org/licenses/OLDAP-1.3.html", "https://spdx.org/licenses/OLDAP-1.3.json",false, false, false),
            new SpdxLicense("Giftware", "Giftware License", "https://spdx.org/licenses/Giftware.html", "https://spdx.org/licenses/Giftware.json",false, false, false),
            new SpdxLicense("BitTorrent-1.1", "BitTorrent Open Source License v1.1", "https://spdx.org/licenses/BitTorrent-1.1.html", "https://spdx.org/licenses/BitTorrent-1.1.json",false, true, false),
            new SpdxLicense("ISC", "ISC License", "https://spdx.org/licenses/ISC.html", "https://spdx.org/licenses/ISC.json",true, true, false),
            new SpdxLicense("LPPL-1.1", "LaTeX Project Public License v1.1", "https://spdx.org/licenses/LPPL-1.1.html", "https://spdx.org/licenses/LPPL-1.1.json",false, false, false),
            new SpdxLicense("ECL-2.0", "Educational Community License v2.0", "https://spdx.org/licenses/ECL-2.0.html", "https://spdx.org/licenses/ECL-2.0.json",true, true, false),
            new SpdxLicense("Entessa", "Entessa Public License v1.0", "https://spdx.org/licenses/Entessa.html", "https://spdx.org/licenses/Entessa.json",true, false, false),
            new SpdxLicense("Spencer-86", "Spencer License 86", "https://spdx.org/licenses/Spencer-86.html", "https://spdx.org/licenses/Spencer-86.json",false, false, false),
            new SpdxLicense("O-UDA-1.0", "Open Use of Data Agreement v1.0", "https://spdx.org/licenses/O-UDA-1.0.html", "https://spdx.org/licenses/O-UDA-1.0.json",false, false, false),
            new SpdxLicense("BSD-4-Clause", "BSD 4-Clause \"Original\" or \"Old\" License", "https://spdx.org/licenses/BSD-4-Clause.html", "https://spdx.org/licenses/BSD-4-Clause.json",false, true, false),
            new SpdxLicense("Condor-1.1", "Condor Public License v1.1", "https://spdx.org/licenses/Condor-1.1.html", "https://spdx.org/licenses/Condor-1.1.json",false, true, false),
            new SpdxLicense("ODC-By-1.0", "Open Data Commons Attribution License v1.0", "https://spdx.org/licenses/ODC-By-1.0.html", "https://spdx.org/licenses/ODC-By-1.0.json",false, false, false),
            new SpdxLicense("IPA", "IPA Font License", "https://spdx.org/licenses/IPA.html", "https://spdx.org/licenses/IPA.json",true, true, false),
            new SpdxLicense("Net-SNMP", "Net-SNMP License", "https://spdx.org/licenses/Net-SNMP.html", "https://spdx.org/licenses/Net-SNMP.json",false, false, false),
            new SpdxLicense("BSD-4-Clause-Shortened", "BSD 4 Clause Shortened", "https://spdx.org/licenses/BSD-4-Clause-Shortened.html", "https://spdx.org/licenses/BSD-4-Clause-Shortened.json",false, false, false),
            new SpdxLicense("CDLA-Permissive-2.0", "Community Data License Agreement Permissive 2.0", "https://spdx.org/licenses/CDLA-Permissive-2.0.html", "https://spdx.org/licenses/CDLA-Permissive-2.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-2.5", "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-2.5.html", "https://spdx.org/licenses/CC-BY-NC-ND-2.5.json",false, false, false),
            new SpdxLicense("BSD-3-Clause-No-Nuclear-License", "BSD 3-Clause No Nuclear License", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.json",false, false, false),
            new SpdxLicense("CC-BY-3.0-NL", "Creative Commons Attribution 3.0 Netherlands", "https://spdx.org/licenses/CC-BY-3.0-NL.html", "https://spdx.org/licenses/CC-BY-3.0-NL.json",false, false, false),
            new SpdxLicense("Latex2e", "Latex2e License", "https://spdx.org/licenses/Latex2e.html", "https://spdx.org/licenses/Latex2e.json",false, false, false),
            new SpdxLicense("OGL-Canada-2.0", "Open Government Licence - Canada", "https://spdx.org/licenses/OGL-Canada-2.0.html", "https://spdx.org/licenses/OGL-Canada-2.0.json",false, false, false),
            new SpdxLicense("GPL-2.0-with-font-exception", "GNU General Public License v2.0 w/Font exception", "https://spdx.org/licenses/GPL-2.0-with-font-exception.html", "https://spdx.org/licenses/GPL-2.0-with-font-exception.json",false, false, true),
            new SpdxLicense("ZPL-2.1", "Zope Public License 2.1", "https://spdx.org/licenses/ZPL-2.1.html", "https://spdx.org/licenses/ZPL-2.1.json",true, true, false),
            new SpdxLicense("BSD-3-Clause-Modification", "BSD 3-Clause Modification", "https://spdx.org/licenses/BSD-3-Clause-Modification.html", "https://spdx.org/licenses/BSD-3-Clause-Modification.json",false, false, false),
            new SpdxLicense("VSL-1.0", "Vovida Software License v1.0", "https://spdx.org/licenses/VSL-1.0.html", "https://spdx.org/licenses/VSL-1.0.json",true, false, false),
            new SpdxLicense("RSA-MD", "RSA Message-Digest License", "https://spdx.org/licenses/RSA-MD.html", "https://spdx.org/licenses/RSA-MD.json",false, false, false),
            new SpdxLicense("CDL-1.0", "Common Documentation License 1.0", "https://spdx.org/licenses/CDL-1.0.html", "https://spdx.org/licenses/CDL-1.0.json",false, false, false),
            new SpdxLicense("Parity-7.0.0", "The Parity Public License 7.0.0", "https://spdx.org/licenses/Parity-7.0.0.html", "https://spdx.org/licenses/Parity-7.0.0.json",false, false, false),
            new SpdxLicense("CC-BY-SA-2.0-UK", "Creative Commons Attribution Share Alike 2.0 England and Wales", "https://spdx.org/licenses/CC-BY-SA-2.0-UK.html", "https://spdx.org/licenses/CC-BY-SA-2.0-UK.json",false, false, false),
            new SpdxLicense("SCEA", "SCEA Shared Source License", "https://spdx.org/licenses/SCEA.html", "https://spdx.org/licenses/SCEA.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-3.0-DE", "Creative Commons Attribution Non Commercial Share Alike 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-DE.html", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-DE.json",false, false, false),
            new SpdxLicense("SHL-0.5", "Solderpad Hardware License v0.5", "https://spdx.org/licenses/SHL-0.5.html", "https://spdx.org/licenses/SHL-0.5.json",false, false, false),
            new SpdxLicense("BSD-3-Clause", "BSD 3-Clause \"New\" or \"Revised\" License", "https://spdx.org/licenses/BSD-3-Clause.html", "https://spdx.org/licenses/BSD-3-Clause.json",true, true, false),
            new SpdxLicense("NLOD-2.0", "Norwegian Licence for Open Government Data (NLOD) 2.0", "https://spdx.org/licenses/NLOD-2.0.html", "https://spdx.org/licenses/NLOD-2.0.json",false, false, false),
            new SpdxLicense("Saxpath", "Saxpath License", "https://spdx.org/licenses/Saxpath.html", "https://spdx.org/licenses/Saxpath.json",false, false, false),
            new SpdxLicense("APAFML", "Adobe Postscript AFM License", "https://spdx.org/licenses/APAFML.html", "https://spdx.org/licenses/APAFML.json",false, false, false),
            new SpdxLicense("Info-ZIP", "Info-ZIP License", "https://spdx.org/licenses/Info-ZIP.html", "https://spdx.org/licenses/Info-ZIP.json",false, false, false),
            new SpdxLicense("APSL-1.1", "Apple Public Source License 1.1", "https://spdx.org/licenses/APSL-1.1.html", "https://spdx.org/licenses/APSL-1.1.json",true, false, false),
            new SpdxLicense("HTMLTIDY", "HTML Tidy License", "https://spdx.org/licenses/HTMLTIDY.html", "https://spdx.org/licenses/HTMLTIDY.json",false, false, false),
            new SpdxLicense("COIL-1.0", "Copyfree Open Innovation License", "https://spdx.org/licenses/COIL-1.0.html", "https://spdx.org/licenses/COIL-1.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-1.0", "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-1.0.html", "https://spdx.org/licenses/CC-BY-NC-SA-1.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-2.0", "Creative Commons Attribution Non Commercial 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-2.0.html", "https://spdx.org/licenses/CC-BY-NC-2.0.json",false, false, false),
            new SpdxLicense("SSH-short", "SSH short notice", "https://spdx.org/licenses/SSH-short.html", "https://spdx.org/licenses/SSH-short.json",false, false, false),
            new SpdxLicense("Mup", "Mup License", "https://spdx.org/licenses/Mup.html", "https://spdx.org/licenses/Mup.json",false, false, false),
            new SpdxLicense("EFL-1.0", "Eiffel Forum License v1.0", "https://spdx.org/licenses/EFL-1.0.html", "https://spdx.org/licenses/EFL-1.0.json",true, false, false),
            new SpdxLicense("LGPL-3.0-only", "GNU Lesser General Public License v3.0 only", "https://spdx.org/licenses/LGPL-3.0-only.html", "https://spdx.org/licenses/LGPL-3.0-only.json",true, true, false),
            new SpdxLicense("NPOSL-3.0", "Non-Profit Open Software License 3.0", "https://spdx.org/licenses/NPOSL-3.0.html", "https://spdx.org/licenses/NPOSL-3.0.json",true, false, false),
            new SpdxLicense("CC-BY-ND-4.0", "Creative Commons Attribution No Derivatives 4.0 International", "https://spdx.org/licenses/CC-BY-ND-4.0.html", "https://spdx.org/licenses/CC-BY-ND-4.0.json",false, false, false),
            new SpdxLicense("Xerox", "Xerox License", "https://spdx.org/licenses/Xerox.html", "https://spdx.org/licenses/Xerox.json",false, false, false),
            new SpdxLicense("OGL-UK-3.0", "Open Government Licence v3.0", "https://spdx.org/licenses/OGL-UK-3.0.html", "https://spdx.org/licenses/OGL-UK-3.0.json",false, false, false),
            new SpdxLicense("AAL", "Attribution Assurance License", "https://spdx.org/licenses/AAL.html", "https://spdx.org/licenses/AAL.json",true, false, false),
            new SpdxLicense("QPL-1.0", "Q Public License 1.0", "https://spdx.org/licenses/QPL-1.0.html", "https://spdx.org/licenses/QPL-1.0.json",true, true, false),
            new SpdxLicense("Dotseqn", "Dotseqn License", "https://spdx.org/licenses/Dotseqn.html", "https://spdx.org/licenses/Dotseqn.json",false, false, false),
            new SpdxLicense("GPL-2.0", "GNU General Public License v2.0 only", "https://spdx.org/licenses/GPL-2.0.html", "https://spdx.org/licenses/GPL-2.0.json",true, true, true),
            new SpdxLicense("libselinux-1.0", "libselinux public domain notice", "https://spdx.org/licenses/libselinux-1.0.html", "https://spdx.org/licenses/libselinux-1.0.json",false, false, false),
            new SpdxLicense("MIT-advertising", "Enlightenment License (e16)", "https://spdx.org/licenses/MIT-advertising.html", "https://spdx.org/licenses/MIT-advertising.json",false, false, false),
            new SpdxLicense("SSH-OpenSSH", "SSH OpenSSH license", "https://spdx.org/licenses/SSH-OpenSSH.html", "https://spdx.org/licenses/SSH-OpenSSH.json",false, false, false),
            new SpdxLicense("LGPLLR", "Lesser General Public License For Linguistic Resources", "https://spdx.org/licenses/LGPLLR.html", "https://spdx.org/licenses/LGPLLR.json",false, false, false),
            new SpdxLicense("ErlPL-1.1", "Erlang Public License v1.1", "https://spdx.org/licenses/ErlPL-1.1.html", "https://spdx.org/licenses/ErlPL-1.1.json",false, false, false),
            new SpdxLicense("BSD-2-Clause-NetBSD", "BSD 2-Clause NetBSD License", "https://spdx.org/licenses/BSD-2-Clause-NetBSD.html", "https://spdx.org/licenses/BSD-2-Clause-NetBSD.json",false, true, true),
            new SpdxLicense("TU-Berlin-2.0", "Technische Universitaet Berlin License 2.0", "https://spdx.org/licenses/TU-Berlin-2.0.html", "https://spdx.org/licenses/TU-Berlin-2.0.json",false, false, false),
            new SpdxLicense("CC-BY-ND-2.0", "Creative Commons Attribution No Derivatives 2.0 Generic", "https://spdx.org/licenses/CC-BY-ND-2.0.html", "https://spdx.org/licenses/CC-BY-ND-2.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-4.0", "Creative Commons Attribution Non Commercial No Derivatives 4.0 International", "https://spdx.org/licenses/CC-BY-NC-ND-4.0.html", "https://spdx.org/licenses/CC-BY-NC-ND-4.0.json",false, false, false),
            new SpdxLicense("Plexus", "Plexus Classworlds License", "https://spdx.org/licenses/Plexus.html", "https://spdx.org/licenses/Plexus.json",false, false, false),
            new SpdxLicense("SPL-1.0", "Sun Public License v1.0", "https://spdx.org/licenses/SPL-1.0.html", "https://spdx.org/licenses/SPL-1.0.json",true, true, false),
            new SpdxLicense("BSD-3-Clause-No-Military-License", "BSD 3-Clause No Military License", "https://spdx.org/licenses/BSD-3-Clause-No-Military-License.html", "https://spdx.org/licenses/BSD-3-Clause-No-Military-License.json",false, false, false),
            new SpdxLicense("CPAL-1.0", "Common Public Attribution License 1.0", "https://spdx.org/licenses/CPAL-1.0.html", "https://spdx.org/licenses/CPAL-1.0.json",true, true, false),
            new SpdxLicense("Apache-1.1", "Apache License 1.1", "https://spdx.org/licenses/Apache-1.1.html", "https://spdx.org/licenses/Apache-1.1.json",true, true, false),
            new SpdxLicense("UPL-1.0", "Universal Permissive License v1.0", "https://spdx.org/licenses/UPL-1.0.html", "https://spdx.org/licenses/UPL-1.0.json",true, true, false),
            new SpdxLicense("GFDL-1.1-no-invariants-or-later", "GNU Free Documentation License v1.1 or later - no invariants", "https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.json",false, false, false),
            new SpdxLicense("GFDL-1.2-invariants-or-later", "GNU Free Documentation License v1.2 or later - invariants", "https://spdx.org/licenses/GFDL-1.2-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.2-invariants-or-later.json",false, false, false),
            new SpdxLicense("mpich2", "mpich2 License", "https://spdx.org/licenses/mpich2.html", "https://spdx.org/licenses/mpich2.json",false, false, false),
            new SpdxLicense("LGPL-2.0-only", "GNU Library General Public License v2 only", "https://spdx.org/licenses/LGPL-2.0-only.html", "https://spdx.org/licenses/LGPL-2.0-only.json",true, false, false),
            new SpdxLicense("eGenix", "eGenix.com Public License 1.1.0", "https://spdx.org/licenses/eGenix.html", "https://spdx.org/licenses/eGenix.json",false, false, false),
            new SpdxLicense("GFDL-1.2-only", "GNU Free Documentation License v1.2 only", "https://spdx.org/licenses/GFDL-1.2-only.html", "https://spdx.org/licenses/GFDL-1.2-only.json",false, true, false),
            new SpdxLicense("Unicode-TOU", "Unicode Terms of Use", "https://spdx.org/licenses/Unicode-TOU.html", "https://spdx.org/licenses/Unicode-TOU.json",false, false, false),
            new SpdxLicense("APSL-1.2", "Apple Public Source License 1.2", "https://spdx.org/licenses/APSL-1.2.html", "https://spdx.org/licenses/APSL-1.2.json",true, false, false),
            new SpdxLicense("Apache-2.0", "Apache License 2.0", "https://spdx.org/licenses/Apache-2.0.html", "https://spdx.org/licenses/Apache-2.0.json",true, true, false),
            new SpdxLicense("BSD-Source-Code", "BSD Source Code Attribution", "https://spdx.org/licenses/BSD-Source-Code.html", "https://spdx.org/licenses/BSD-Source-Code.json",false, false, false),
            new SpdxLicense("CC-BY-NC-4.0", "Creative Commons Attribution Non Commercial 4.0 International", "https://spdx.org/licenses/CC-BY-NC-4.0.html", "https://spdx.org/licenses/CC-BY-NC-4.0.json",false, false, false),
            new SpdxLicense("TMate", "TMate Open Source License", "https://spdx.org/licenses/TMate.html", "https://spdx.org/licenses/TMate.json",false, false, false),
            new SpdxLicense("OPL-1.0", "Open Public License v1.0", "https://spdx.org/licenses/OPL-1.0.html", "https://spdx.org/licenses/OPL-1.0.json",false, false, false),
            new SpdxLicense("CECILL-1.0", "CeCILL Free Software License Agreement v1.0", "https://spdx.org/licenses/CECILL-1.0.html", "https://spdx.org/licenses/CECILL-1.0.json",false, false, false),
            new SpdxLicense("EPL-2.0", "Eclipse Public License 2.0", "https://spdx.org/licenses/EPL-2.0.html", "https://spdx.org/licenses/EPL-2.0.json",true, true, false),
            new SpdxLicense("LPPL-1.3c", "LaTeX Project Public License v1.3c", "https://spdx.org/licenses/LPPL-1.3c.html", "https://spdx.org/licenses/LPPL-1.3c.json",true, false, false),
            new SpdxLicense("Zed", "Zed License", "https://spdx.org/licenses/Zed.html", "https://spdx.org/licenses/Zed.json",false, false, false),
            new SpdxLicense("SGI-B-2.0", "SGI Free Software License B v2.0", "https://spdx.org/licenses/SGI-B-2.0.html", "https://spdx.org/licenses/SGI-B-2.0.json",false, true, false),
            new SpdxLicense("BSD-3-Clause-Open-MPI", "BSD 3-Clause Open MPI variant", "https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html", "https://spdx.org/licenses/BSD-3-Clause-Open-MPI.json",false, false, false),
            new SpdxLicense("CDDL-1.0", "Common Development and Distribution License 1.0", "https://spdx.org/licenses/CDDL-1.0.html", "https://spdx.org/licenses/CDDL-1.0.json",true, true, false),
            new SpdxLicense("GFDL-1.2-or-later", "GNU Free Documentation License v1.2 or later", "https://spdx.org/licenses/GFDL-1.2-or-later.html", "https://spdx.org/licenses/GFDL-1.2-or-later.json",false, true, false),
            new SpdxLicense("Hippocratic-2.1", "Hippocratic License 2.1", "https://spdx.org/licenses/Hippocratic-2.1.html", "https://spdx.org/licenses/Hippocratic-2.1.json",false, false, false),
            new SpdxLicense("Linux-OpenIB", "Linux Kernel Variant of OpenIB.org license", "https://spdx.org/licenses/Linux-OpenIB.html", "https://spdx.org/licenses/Linux-OpenIB.json",false, false, false),
            new SpdxLicense("IJG", "Independent JPEG Group License", "https://spdx.org/licenses/IJG.html", "https://spdx.org/licenses/IJG.json",false, true, false),
            new SpdxLicense("SchemeReport", "Scheme Language Report License", "https://spdx.org/licenses/SchemeReport.html", "https://spdx.org/licenses/SchemeReport.json",false, false, false),
            new SpdxLicense("TCL", "TCL/TK License", "https://spdx.org/licenses/TCL.html", "https://spdx.org/licenses/TCL.json",false, false, false),
            new SpdxLicense("Linux-man-pages-copyleft", "Linux man-pages Copyleft", "https://spdx.org/licenses/Linux-man-pages-copyleft.html", "https://spdx.org/licenses/Linux-man-pages-copyleft.json",false, false, false),
            new SpdxLicense("NBPL-1.0", "Net Boolean Public License v1", "https://spdx.org/licenses/NBPL-1.0.html", "https://spdx.org/licenses/NBPL-1.0.json",false, false, false),
            new SpdxLicense("Zimbra-1.3", "Zimbra Public License v1.3", "https://spdx.org/licenses/Zimbra-1.3.html", "https://spdx.org/licenses/Zimbra-1.3.json",false, true, false),
            new SpdxLicense("MPL-1.0", "Mozilla Public License 1.0", "https://spdx.org/licenses/MPL-1.0.html", "https://spdx.org/licenses/MPL-1.0.json",true, false, false),
            new SpdxLicense("LGPL-2.1-or-later", "GNU Lesser General Public License v2.1 or later", "https://spdx.org/licenses/LGPL-2.1-or-later.html", "https://spdx.org/licenses/LGPL-2.1-or-later.json",true, true, false),
            new SpdxLicense("CC-PDDC", "Creative Commons Public Domain Dedication and Certification", "https://spdx.org/licenses/CC-PDDC.html", "https://spdx.org/licenses/CC-PDDC.json",false, false, false),
            new SpdxLicense("Imlib2", "Imlib2 License", "https://spdx.org/licenses/Imlib2.html", "https://spdx.org/licenses/Imlib2.json",false, true, false),
            new SpdxLicense("Multics", "Multics License", "https://spdx.org/licenses/Multics.html", "https://spdx.org/licenses/Multics.json",true, false, false),
            new SpdxLicense("D-FSL-1.0", "Deutsche Freie Software Lizenz", "https://spdx.org/licenses/D-FSL-1.0.html", "https://spdx.org/licenses/D-FSL-1.0.json",false, false, false),
            new SpdxLicense("BSD-3-Clause-No-Nuclear-Warranty", "BSD 3-Clause No Nuclear Warranty", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-Warranty.html", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-Warranty.json",false, false, false),
            new SpdxLicense("BlueOak-1.0.0", "Blue Oak Model License 1.0.0", "https://spdx.org/licenses/BlueOak-1.0.0.html", "https://spdx.org/licenses/BlueOak-1.0.0.json",false, false, false),
            new SpdxLicense("Community-Spec-1.0", "Community Specification License 1.0", "https://spdx.org/licenses/Community-Spec-1.0.html", "https://spdx.org/licenses/Community-Spec-1.0.json",false, false, false),
            new SpdxLicense("GFDL-1.1-only", "GNU Free Documentation License v1.1 only", "https://spdx.org/licenses/GFDL-1.1-only.html", "https://spdx.org/licenses/GFDL-1.1-only.json",false, true, false),
            new SpdxLicense("RPL-1.5", "Reciprocal Public License 1.5", "https://spdx.org/licenses/RPL-1.5.html", "https://spdx.org/licenses/RPL-1.5.json",true, false, false),
            new SpdxLicense("OFL-1.1", "SIL Open Font License 1.1", "https://spdx.org/licenses/OFL-1.1.html", "https://spdx.org/licenses/OFL-1.1.json",true, true, false),
            new SpdxLicense("CPL-1.0", "Common Public License 1.0", "https://spdx.org/licenses/CPL-1.0.html", "https://spdx.org/licenses/CPL-1.0.json",true, true, false),
            new SpdxLicense("AGPL-3.0-only", "GNU Affero General Public License v3.0 only", "https://spdx.org/licenses/AGPL-3.0-only.html", "https://spdx.org/licenses/AGPL-3.0-only.json",true, true, false),
            new SpdxLicense("gnuplot", "gnuplot License", "https://spdx.org/licenses/gnuplot.html", "https://spdx.org/licenses/gnuplot.json",false, true, false),
            new SpdxLicense("NLPL", "No Limit Public License", "https://spdx.org/licenses/NLPL.html", "https://spdx.org/licenses/NLPL.json",false, false, false),
            new SpdxLicense("ADSL", "Amazon Digital Services License", "https://spdx.org/licenses/ADSL.html", "https://spdx.org/licenses/ADSL.json",false, false, false),
            new SpdxLicense("psfrag", "psfrag License", "https://spdx.org/licenses/psfrag.html", "https://spdx.org/licenses/psfrag.json",false, false, false),
            new SpdxLicense("Watcom-1.0", "Sybase Open Watcom Public License 1.0", "https://spdx.org/licenses/Watcom-1.0.html", "https://spdx.org/licenses/Watcom-1.0.json",true, false, false),
            new SpdxLicense("SGI-B-1.0", "SGI Free Software License B v1.0", "https://spdx.org/licenses/SGI-B-1.0.html", "https://spdx.org/licenses/SGI-B-1.0.json",false, false, false),
            new SpdxLicense("W3C-19980720", "W3C Software Notice and License (1998-07-20)", "https://spdx.org/licenses/W3C-19980720.html", "https://spdx.org/licenses/W3C-19980720.json",false, false, false),
            new SpdxLicense("NASA-1.3", "NASA Open Source Agreement 1.3", "https://spdx.org/licenses/NASA-1.3.html", "https://spdx.org/licenses/NASA-1.3.json",true, false, false),
            new SpdxLicense("Fair", "Fair License", "https://spdx.org/licenses/Fair.html", "https://spdx.org/licenses/Fair.json",true, false, false),
            new SpdxLicense("CERN-OHL-1.1", "CERN Open Hardware Licence v1.1", "https://spdx.org/licenses/CERN-OHL-1.1.html", "https://spdx.org/licenses/CERN-OHL-1.1.json",false, false, false),
            new SpdxLicense("LGPL-3.0+", "GNU Lesser General Public License v3.0 or later", "https://spdx.org/licenses/LGPL-3.0+.html", "https://spdx.org/licenses/LGPL-3.0+.json",true, true, true),
            new SpdxLicense("LGPL-3.0", "GNU Lesser General Public License v3.0 only", "https://spdx.org/licenses/LGPL-3.0.html", "https://spdx.org/licenses/LGPL-3.0.json",true, true, true),
            new SpdxLicense("BSD-2-Clause-Views", "BSD 2-Clause with views sentence", "https://spdx.org/licenses/BSD-2-Clause-Views.html", "https://spdx.org/licenses/BSD-2-Clause-Views.json",false, false, false),
            new SpdxLicense("OLDAP-1.1", "Open LDAP Public License v1.1", "https://spdx.org/licenses/OLDAP-1.1.html", "https://spdx.org/licenses/OLDAP-1.1.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-3.0-DE", "Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-DE.html", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-DE.json",false, false, false),
            new SpdxLicense("OGDL-Taiwan-1.0", "Taiwan Open Government Data License, version 1.0", "https://spdx.org/licenses/OGDL-Taiwan-1.0.html", "https://spdx.org/licenses/OGDL-Taiwan-1.0.json",false, false, false),
            new SpdxLicense("NGPL", "Nethack General Public License", "https://spdx.org/licenses/NGPL.html", "https://spdx.org/licenses/NGPL.json",true, false, false),
            new SpdxLicense("BSL-1.0", "Boost Software License 1.0", "https://spdx.org/licenses/BSL-1.0.html", "https://spdx.org/licenses/BSL-1.0.json",true, true, false),
            new SpdxLicense("Sendmail", "Sendmail License", "https://spdx.org/licenses/Sendmail.html", "https://spdx.org/licenses/Sendmail.json",false, false, false),
            new SpdxLicense("OLDAP-2.4", "Open LDAP Public License v2.4", "https://spdx.org/licenses/OLDAP-2.4.html", "https://spdx.org/licenses/OLDAP-2.4.json",false, false, false),
            new SpdxLicense("CrystalStacker", "CrystalStacker License", "https://spdx.org/licenses/CrystalStacker.html", "https://spdx.org/licenses/CrystalStacker.json",false, false, false),
            new SpdxLicense("blessing", "SQLite Blessing", "https://spdx.org/licenses/blessing.html", "https://spdx.org/licenses/blessing.json",false, false, false),
            new SpdxLicense("CC-BY-SA-4.0", "Creative Commons Attribution Share Alike 4.0 International", "https://spdx.org/licenses/CC-BY-SA-4.0.html", "https://spdx.org/licenses/CC-BY-SA-4.0.json",false, true, false),
            new SpdxLicense("CC-BY-2.5", "Creative Commons Attribution 2.5 Generic", "https://spdx.org/licenses/CC-BY-2.5.html", "https://spdx.org/licenses/CC-BY-2.5.json",false, false, false),
            new SpdxLicense("ICU", "ICU License", "https://spdx.org/licenses/ICU.html", "https://spdx.org/licenses/ICU.json",false, false, false),
            new SpdxLicense("diffmark", "diffmark license", "https://spdx.org/licenses/diffmark.html", "https://spdx.org/licenses/diffmark.json",false, false, false),
            new SpdxLicense("libpng-2.0", "PNG Reference Library version 2", "https://spdx.org/licenses/libpng-2.0.html", "https://spdx.org/licenses/libpng-2.0.json",false, false, false),
            new SpdxLicense("GPL-1.0+", "GNU General Public License v1.0 or later", "https://spdx.org/licenses/GPL-1.0+.html", "https://spdx.org/licenses/GPL-1.0+.json",false, false, true),
            new SpdxLicense("RSCPL", "Ricoh Source Code Public License", "https://spdx.org/licenses/RSCPL.html", "https://spdx.org/licenses/RSCPL.json",true, false, false),
            new SpdxLicense("FSFAP", "FSF All Permissive License", "https://spdx.org/licenses/FSFAP.html", "https://spdx.org/licenses/FSFAP.json",false, true, false),
            new SpdxLicense("NPL-1.1", "Netscape Public License v1.1", "https://spdx.org/licenses/NPL-1.1.html", "https://spdx.org/licenses/NPL-1.1.json",false, true, false),
            new SpdxLicense("OSL-1.1", "Open Software License 1.1", "https://spdx.org/licenses/OSL-1.1.html", "https://spdx.org/licenses/OSL-1.1.json",false, true, false),
            new SpdxLicense("MIT-feh", "feh License", "https://spdx.org/licenses/MIT-feh.html", "https://spdx.org/licenses/MIT-feh.json",false, false, false),
            new SpdxLicense("PDDL-1.0", "Open Data Commons Public Domain Dedication & License 1.0", "https://spdx.org/licenses/PDDL-1.0.html", "https://spdx.org/licenses/PDDL-1.0.json",false, false, false),
            new SpdxLicense("CERN-OHL-1.2", "CERN Open Hardware Licence v1.2", "https://spdx.org/licenses/CERN-OHL-1.2.html", "https://spdx.org/licenses/CERN-OHL-1.2.json",false, false, false),
            new SpdxLicense("CC-BY-3.0", "Creative Commons Attribution 3.0 Unported", "https://spdx.org/licenses/CC-BY-3.0.html", "https://spdx.org/licenses/CC-BY-3.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-2.0", "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-2.0.html", "https://spdx.org/licenses/CC-BY-NC-ND-2.0.json",false, false, false),
            new SpdxLicense("GFDL-1.1-or-later", "GNU Free Documentation License v1.1 or later", "https://spdx.org/licenses/GFDL-1.1-or-later.html", "https://spdx.org/licenses/GFDL-1.1-or-later.json",false, true, false),
            new SpdxLicense("Borceux", "Borceux license", "https://spdx.org/licenses/Borceux.html", "https://spdx.org/licenses/Borceux.json",false, false, false),
            new SpdxLicense("NCSA", "University of Illinois/NCSA Open Source License", "https://spdx.org/licenses/NCSA.html", "https://spdx.org/licenses/NCSA.json",true, true, false),
            new SpdxLicense("Naumen", "Naumen Public License", "https://spdx.org/licenses/Naumen.html", "https://spdx.org/licenses/Naumen.json",true, false, false),
            new SpdxLicense("Caldera", "Caldera License", "https://spdx.org/licenses/Caldera.html", "https://spdx.org/licenses/Caldera.json",false, false, false),
            new SpdxLicense("PHP-3.01", "PHP License v3.01", "https://spdx.org/licenses/PHP-3.01.html", "https://spdx.org/licenses/PHP-3.01.json",true, true, false),
            new SpdxLicense("GPL-3.0", "GNU General Public License v3.0 only", "https://spdx.org/licenses/GPL-3.0.html", "https://spdx.org/licenses/GPL-3.0.json",true, true, true),
            new SpdxLicense("GFDL-1.1-no-invariants-only", "GNU Free Documentation License v1.1 only - no invariants", "https://spdx.org/licenses/GFDL-1.1-no-invariants-only.html", "https://spdx.org/licenses/GFDL-1.1-no-invariants-only.json",false, false, false),
            new SpdxLicense("DOC", "DOC License", "https://spdx.org/licenses/DOC.html", "https://spdx.org/licenses/DOC.json",false, false, false),
            new SpdxLicense("OGC-1.0", "OGC Software License, Version 1.0", "https://spdx.org/licenses/OGC-1.0.html", "https://spdx.org/licenses/OGC-1.0.json",false, false, false),
            new SpdxLicense("GPL-3.0-or-later", "GNU General Public License v3.0 or later", "https://spdx.org/licenses/GPL-3.0-or-later.html", "https://spdx.org/licenses/GPL-3.0-or-later.json",true, true, false),
            new SpdxLicense("SAX-PD", "Sax Public Domain Notice", "https://spdx.org/licenses/SAX-PD.html", "https://spdx.org/licenses/SAX-PD.json",false, false, false),
            new SpdxLicense("CNRI-Python", "CNRI Python License", "https://spdx.org/licenses/CNRI-Python.html", "https://spdx.org/licenses/CNRI-Python.json",true, false, false),
            new SpdxLicense("HPND", "Historical Permission Notice and Disclaimer", "https://spdx.org/licenses/HPND.html", "https://spdx.org/licenses/HPND.json",true, true, false),
            new SpdxLicense("CECILL-C", "CeCILL-C Free Software License Agreement", "https://spdx.org/licenses/CECILL-C.html", "https://spdx.org/licenses/CECILL-C.json",false, true, false),
            new SpdxLicense("GPL-2.0-only", "GNU General Public License v2.0 only", "https://spdx.org/licenses/GPL-2.0-only.html", "https://spdx.org/licenses/GPL-2.0-only.json",true, true, false),
            new SpdxLicense("PSF-2.0", "Python Software Foundation License 2.0", "https://spdx.org/licenses/PSF-2.0.html", "https://spdx.org/licenses/PSF-2.0.json",false, false, false),
            new SpdxLicense("OFL-1.1-no-RFN", "SIL Open Font License 1.1 with no Reserved Font Name", "https://spdx.org/licenses/OFL-1.1-no-RFN.html", "https://spdx.org/licenses/OFL-1.1-no-RFN.json",true, false, false),
            new SpdxLicense("W3C", "W3C Software Notice and License (2002-12-31)", "https://spdx.org/licenses/W3C.html", "https://spdx.org/licenses/W3C.json",true, true, false),
            new SpdxLicense("OFL-1.0-no-RFN", "SIL Open Font License 1.0 with no Reserved Font Name", "https://spdx.org/licenses/OFL-1.0-no-RFN.html", "https://spdx.org/licenses/OFL-1.0-no-RFN.json",false, false, false),
            new SpdxLicense("xinetd", "xinetd License", "https://spdx.org/licenses/xinetd.html", "https://spdx.org/licenses/xinetd.json",false, true, false),
            new SpdxLicense("OGTSL", "Open Group Test Suite License", "https://spdx.org/licenses/OGTSL.html", "https://spdx.org/licenses/OGTSL.json",true, false, false),
            new SpdxLicense("GFDL-1.3", "GNU Free Documentation License v1.3", "https://spdx.org/licenses/GFDL-1.3.html", "https://spdx.org/licenses/GFDL-1.3.json",false, true, true),
            new SpdxLicense("AGPL-1.0-only", "Affero General Public License v1.0 only", "https://spdx.org/licenses/AGPL-1.0-only.html", "https://spdx.org/licenses/AGPL-1.0-only.json",false, false, false),
            new SpdxLicense("WTFPL", "Do What The F*ck You Want To Public License", "https://spdx.org/licenses/WTFPL.html", "https://spdx.org/licenses/WTFPL.json",false, true, false),
            new SpdxLicense("W3C-20150513", "W3C Software Notice and Document License (2015-05-13)", "https://spdx.org/licenses/W3C-20150513.html", "https://spdx.org/licenses/W3C-20150513.json",false, false, false),
            new SpdxLicense("Sleepycat", "Sleepycat License", "https://spdx.org/licenses/Sleepycat.html", "https://spdx.org/licenses/Sleepycat.json",true, true, false),
            new SpdxLicense("JasPer-2.0", "JasPer License", "https://spdx.org/licenses/JasPer-2.0.html", "https://spdx.org/licenses/JasPer-2.0.json",false, false, false),
            new SpdxLicense("Nokia", "Nokia Open Source License", "https://spdx.org/licenses/Nokia.html", "https://spdx.org/licenses/Nokia.json",true, true, false),
            new SpdxLicense("LGPL-2.1+", "GNU Library General Public License v2.1 or later", "https://spdx.org/licenses/LGPL-2.1+.html", "https://spdx.org/licenses/LGPL-2.1+.json",true, true, true),
            new SpdxLicense("OGL-UK-2.0", "Open Government Licence v2.0", "https://spdx.org/licenses/OGL-UK-2.0.html", "https://spdx.org/licenses/OGL-UK-2.0.json",false, false, false),
            new SpdxLicense("RPL-1.1", "Reciprocal Public License 1.1", "https://spdx.org/licenses/RPL-1.1.html", "https://spdx.org/licenses/RPL-1.1.json",true, false, false),
            new SpdxLicense("SHL-0.51", "Solderpad Hardware License, Version 0.51", "https://spdx.org/licenses/SHL-0.51.html", "https://spdx.org/licenses/SHL-0.51.json",false, false, false),
            new SpdxLicense("LiLiQ-P-1.1", "Licence Libre du Québec – Permissive version 1.1", "https://spdx.org/licenses/LiLiQ-P-1.1.html", "https://spdx.org/licenses/LiLiQ-P-1.1.json",true, false, false),
            new SpdxLicense("OpenSSL", "OpenSSL License", "https://spdx.org/licenses/OpenSSL.html", "https://spdx.org/licenses/OpenSSL.json",false, true, false),
            new SpdxLicense("C-UDA-1.0", "Computational Use of Data Agreement v1.0", "https://spdx.org/licenses/C-UDA-1.0.html", "https://spdx.org/licenses/C-UDA-1.0.json",false, false, false),
            new SpdxLicense("Xnet", "X.Net License", "https://spdx.org/licenses/Xnet.html", "https://spdx.org/licenses/Xnet.json",true, false, false),
            new SpdxLicense("APSL-2.0", "Apple Public Source License 2.0", "https://spdx.org/licenses/APSL-2.0.html", "https://spdx.org/licenses/APSL-2.0.json",true, true, false),
            new SpdxLicense("FreeBSD-DOC", "FreeBSD Documentation License", "https://spdx.org/licenses/FreeBSD-DOC.html", "https://spdx.org/licenses/FreeBSD-DOC.json",false, false, false),
            new SpdxLicense("NPL-1.0", "Netscape Public License v1.0", "https://spdx.org/licenses/NPL-1.0.html", "https://spdx.org/licenses/NPL-1.0.json",false, true, false),
            new SpdxLicense("GPL-2.0-or-later", "GNU General Public License v2.0 or later", "https://spdx.org/licenses/GPL-2.0-or-later.html", "https://spdx.org/licenses/GPL-2.0-or-later.json",true, true, false),
            new SpdxLicense("CECILL-2.0", "CeCILL Free Software License Agreement v2.0", "https://spdx.org/licenses/CECILL-2.0.html", "https://spdx.org/licenses/CECILL-2.0.json",false, true, false),
            new SpdxLicense("OFL-1.0", "SIL Open Font License 1.0", "https://spdx.org/licenses/OFL-1.0.html", "https://spdx.org/licenses/OFL-1.0.json",false, true, false),
            new SpdxLicense("EPL-1.0", "Eclipse Public License 1.0", "https://spdx.org/licenses/EPL-1.0.html", "https://spdx.org/licenses/EPL-1.0.json",true, true, false),
            new SpdxLicense("NOSL", "Netizen Open Source License", "https://spdx.org/licenses/NOSL.html", "https://spdx.org/licenses/NOSL.json",false, true, false),
            new SpdxLicense("MIT-CMU", "CMU License", "https://spdx.org/licenses/MIT-CMU.html", "https://spdx.org/licenses/MIT-CMU.json",false, false, false),
            new SpdxLicense("CERN-OHL-S-2.0", "CERN Open Hardware Licence Version 2 - Strongly Reciprocal", "https://spdx.org/licenses/CERN-OHL-S-2.0.html", "https://spdx.org/licenses/CERN-OHL-S-2.0.json",true, false, false),
            new SpdxLicense("SWL", "Scheme Widget Library (SWL) Software License Agreement", "https://spdx.org/licenses/SWL.html", "https://spdx.org/licenses/SWL.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-2.5", "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-2.5.html", "https://spdx.org/licenses/CC-BY-NC-SA-2.5.json",false, false, false),
            new SpdxLicense("Zlib", "zlib License", "https://spdx.org/licenses/Zlib.html", "https://spdx.org/licenses/Zlib.json",true, true, false),
            new SpdxLicense("CC-BY-NC-SA-3.0", "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-SA-3.0.html", "https://spdx.org/licenses/CC-BY-NC-SA-3.0.json",false, false, false),
            new SpdxLicense("iMatix", "iMatix Standard Function Library Agreement", "https://spdx.org/licenses/iMatix.html", "https://spdx.org/licenses/iMatix.json",false, true, false),
            new SpdxLicense("CC-BY-ND-2.5", "Creative Commons Attribution No Derivatives 2.5 Generic", "https://spdx.org/licenses/CC-BY-ND-2.5.html", "https://spdx.org/licenses/CC-BY-ND-2.5.json",false, false, false),
            new SpdxLicense("PHP-3.0", "PHP License v3.0", "https://spdx.org/licenses/PHP-3.0.html", "https://spdx.org/licenses/PHP-3.0.json",true, false, false),
            new SpdxLicense("Barr", "Barr License", "https://spdx.org/licenses/Barr.html", "https://spdx.org/licenses/Barr.json",false, false, false),
            new SpdxLicense("curl", "curl License", "https://spdx.org/licenses/curl.html", "https://spdx.org/licenses/curl.json",false, false, false),
            new SpdxLicense("Zimbra-1.4", "Zimbra Public License v1.4", "https://spdx.org/licenses/Zimbra-1.4.html", "https://spdx.org/licenses/Zimbra-1.4.json",false, false, false),
            new SpdxLicense("TOSL", "Trusster Open Source License", "https://spdx.org/licenses/TOSL.html", "https://spdx.org/licenses/TOSL.json",false, false, false),
            new SpdxLicense("GPL-3.0-with-GCC-exception", "GNU General Public License v3.0 w/GCC Runtime Library exception", "https://spdx.org/licenses/GPL-3.0-with-GCC-exception.html", "https://spdx.org/licenses/GPL-3.0-with-GCC-exception.json",true, false, true),
            new SpdxLicense("AFL-1.2", "Academic Free License v1.2", "https://spdx.org/licenses/AFL-1.2.html", "https://spdx.org/licenses/AFL-1.2.json",true, true, false),
            new SpdxLicense("GFDL-1.2", "GNU Free Documentation License v1.2", "https://spdx.org/licenses/GFDL-1.2.html", "https://spdx.org/licenses/GFDL-1.2.json",false, true, true),
            new SpdxLicense("CC-BY-ND-3.0-DE", "Creative Commons Attribution No Derivatives 3.0 Germany", "https://spdx.org/licenses/CC-BY-ND-3.0-DE.html", "https://spdx.org/licenses/CC-BY-ND-3.0-DE.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-2.0", "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-2.0.html", "https://spdx.org/licenses/CC-BY-NC-SA-2.0.json",false, false, false),
            new SpdxLicense("GFDL-1.3-invariants-only", "GNU Free Documentation License v1.3 only - invariants", "https://spdx.org/licenses/GFDL-1.3-invariants-only.html", "https://spdx.org/licenses/GFDL-1.3-invariants-only.json",false, false, false),
            new SpdxLicense("GD", "GD License", "https://spdx.org/licenses/GD.html", "https://spdx.org/licenses/GD.json",false, false, false),
            new SpdxLicense("OLDAP-2.3", "Open LDAP Public License v2.3", "https://spdx.org/licenses/OLDAP-2.3.html", "https://spdx.org/licenses/OLDAP-2.3.json",false, true, false),
            new SpdxLicense("Unicode-DFS-2016", "Unicode License Agreement - Data Files and Software (2016)", "https://spdx.org/licenses/Unicode-DFS-2016.html", "https://spdx.org/licenses/Unicode-DFS-2016.json",true, false, false),
            new SpdxLicense("IBM-pibs", "IBM PowerPC Initialization and Boot Software", "https://spdx.org/licenses/IBM-pibs.html", "https://spdx.org/licenses/IBM-pibs.json",false, false, false),
            new SpdxLicense("FDK-AAC", "Fraunhofer FDK AAC Codec Library", "https://spdx.org/licenses/FDK-AAC.html", "https://spdx.org/licenses/FDK-AAC.json",false, false, false),
            new SpdxLicense("CATOSL-1.1", "Computer Associates Trusted Open Source License 1.1", "https://spdx.org/licenses/CATOSL-1.1.html", "https://spdx.org/licenses/CATOSL-1.1.json",true, false, false),
            new SpdxLicense("CC-BY-NC-ND-1.0", "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-1.0.html", "https://spdx.org/licenses/CC-BY-NC-ND-1.0.json",false, false, false),
            new SpdxLicense("DSDP", "DSDP License", "https://spdx.org/licenses/DSDP.html", "https://spdx.org/licenses/DSDP.json",false, false, false),
            new SpdxLicense("BSD-2-Clause-Patent", "BSD-2-Clause Plus Patent License", "https://spdx.org/licenses/BSD-2-Clause-Patent.html", "https://spdx.org/licenses/BSD-2-Clause-Patent.json",true, false, false),
            new SpdxLicense("SugarCRM-1.1.3", "SugarCRM Public License v1.1.3", "https://spdx.org/licenses/SugarCRM-1.1.3.html", "https://spdx.org/licenses/SugarCRM-1.1.3.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-2.0-UK", "Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-UK.html", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-UK.json",false, false, false),
            new SpdxLicense("CC-BY-NC-2.5", "Creative Commons Attribution Non Commercial 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-2.5.html", "https://spdx.org/licenses/CC-BY-NC-2.5.json",false, false, false),
            new SpdxLicense("Unlicense", "The Unlicense", "https://spdx.org/licenses/Unlicense.html", "https://spdx.org/licenses/Unlicense.json",true, true, false),
            new SpdxLicense("AGPL-1.0-or-later", "Affero General Public License v1.0 or later", "https://spdx.org/licenses/AGPL-1.0-or-later.html", "https://spdx.org/licenses/AGPL-1.0-or-later.json",false, false, false),
            new SpdxLicense("GL2PS", "GL2PS License", "https://spdx.org/licenses/GL2PS.html", "https://spdx.org/licenses/GL2PS.json",false, false, false),
            new SpdxLicense("zlib-acknowledgement", "zlib/libpng License with Acknowledgement", "https://spdx.org/licenses/zlib-acknowledgement.html", "https://spdx.org/licenses/zlib-acknowledgement.json",false, false, false),
            new SpdxLicense("TU-Berlin-1.0", "Technische Universitaet Berlin License 1.0", "https://spdx.org/licenses/TU-Berlin-1.0.html", "https://spdx.org/licenses/TU-Berlin-1.0.json",false, false, false),
            new SpdxLicense("Apache-1.0", "Apache License 1.0", "https://spdx.org/licenses/Apache-1.0.html", "https://spdx.org/licenses/Apache-1.0.json",false, true, false),
            new SpdxLicense("Crossword", "Crossword License", "https://spdx.org/licenses/Crossword.html", "https://spdx.org/licenses/Crossword.json",false, false, false),
            new SpdxLicense("HPND-sell-variant", "Historical Permission Notice and Disclaimer - sell variant", "https://spdx.org/licenses/HPND-sell-variant.html", "https://spdx.org/licenses/HPND-sell-variant.json",false, false, false),
            new SpdxLicense("BSD-2-Clause", "BSD 2-Clause \"Simplified\" License", "https://spdx.org/licenses/BSD-2-Clause.html", "https://spdx.org/licenses/BSD-2-Clause.json",true, true, false),
            new SpdxLicense("CC-BY-SA-3.0-DE", "Creative Commons Attribution Share Alike 3.0 Germany", "https://spdx.org/licenses/CC-BY-SA-3.0-DE.html", "https://spdx.org/licenses/CC-BY-SA-3.0-DE.json",false, false, false),
            new SpdxLicense("AMPAS", "Academy of Motion Picture Arts and Sciences BSD", "https://spdx.org/licenses/AMPAS.html", "https://spdx.org/licenses/AMPAS.json",false, false, false),
            new SpdxLicense("YPL-1.1", "Yahoo! Public License v1.1", "https://spdx.org/licenses/YPL-1.1.html", "https://spdx.org/licenses/YPL-1.1.json",false, true, false),
            new SpdxLicense("CC-BY-NC-SA-4.0", "Creative Commons Attribution Non Commercial Share Alike 4.0 International", "https://spdx.org/licenses/CC-BY-NC-SA-4.0.html", "https://spdx.org/licenses/CC-BY-NC-SA-4.0.json",false, false, false),
            new SpdxLicense("Glide", "3dfx Glide License", "https://spdx.org/licenses/Glide.html", "https://spdx.org/licenses/Glide.json",false, false, false),
            new SpdxLicense("Artistic-1.0", "Artistic License 1.0", "https://spdx.org/licenses/Artistic-1.0.html", "https://spdx.org/licenses/Artistic-1.0.json",true, false, false),
            new SpdxLicense("OSL-1.0", "Open Software License 1.0", "https://spdx.org/licenses/OSL-1.0.html", "https://spdx.org/licenses/OSL-1.0.json",true, true, false),
            new SpdxLicense("0BSD", "BSD Zero Clause License", "https://spdx.org/licenses/0BSD.html", "https://spdx.org/licenses/0BSD.json",true, false, false),
            new SpdxLicense("OLDAP-2.7", "Open LDAP Public License v2.7", "https://spdx.org/licenses/OLDAP-2.7.html", "https://spdx.org/licenses/OLDAP-2.7.json",false, true, false),
            new SpdxLicense("TAPR-OHL-1.0", "TAPR Open Hardware License v1.0", "https://spdx.org/licenses/TAPR-OHL-1.0.html", "https://spdx.org/licenses/TAPR-OHL-1.0.json",false, false, false),
            new SpdxLicense("Adobe-2006", "Adobe Systems Incorporated Source Code License Agreement", "https://spdx.org/licenses/Adobe-2006.html", "https://spdx.org/licenses/Adobe-2006.json",false, false, false),
            new SpdxLicense("AFL-1.1", "Academic Free License v1.1", "https://spdx.org/licenses/AFL-1.1.html", "https://spdx.org/licenses/AFL-1.1.json",true, true, false),
            new SpdxLicense("Spencer-94", "Spencer License 94", "https://spdx.org/licenses/Spencer-94.html", "https://spdx.org/licenses/Spencer-94.json",false, false, false),
            new SpdxLicense("XSkat", "XSkat License", "https://spdx.org/licenses/XSkat.html", "https://spdx.org/licenses/XSkat.json",false, false, false),
            new SpdxLicense("Newsletr", "Newsletr License", "https://spdx.org/licenses/Newsletr.html", "https://spdx.org/licenses/Newsletr.json",false, false, false),
            new SpdxLicense("CC-BY-SA-2.0", "Creative Commons Attribution Share Alike 2.0 Generic", "https://spdx.org/licenses/CC-BY-SA-2.0.html", "https://spdx.org/licenses/CC-BY-SA-2.0.json",false, false, false),
            new SpdxLicense("ZPL-1.1", "Zope Public License 1.1", "https://spdx.org/licenses/ZPL-1.1.html", "https://spdx.org/licenses/ZPL-1.1.json",false, false, false),
            new SpdxLicense("GFDL-1.3-only", "GNU Free Documentation License v1.3 only", "https://spdx.org/licenses/GFDL-1.3-only.html", "https://spdx.org/licenses/GFDL-1.3-only.json",false, true, false),
            new SpdxLicense("EUPL-1.0", "European Union Public License 1.0", "https://spdx.org/licenses/EUPL-1.0.html", "https://spdx.org/licenses/EUPL-1.0.json",false, false, false),
            new SpdxLicense("BSD-3-Clause-Clear", "BSD 3-Clause Clear License", "https://spdx.org/licenses/BSD-3-Clause-Clear.html", "https://spdx.org/licenses/BSD-3-Clause-Clear.json",false, true, false),
            new SpdxLicense("GPL-1.0-or-later", "GNU General Public License v1.0 or later", "https://spdx.org/licenses/GPL-1.0-or-later.html", "https://spdx.org/licenses/GPL-1.0-or-later.json",false, false, false),
            new SpdxLicense("CNRI-Jython", "CNRI Jython License", "https://spdx.org/licenses/CNRI-Jython.html", "https://spdx.org/licenses/CNRI-Jython.json",false, false, false),
            new SpdxLicense("Adobe-Glyph", "Adobe Glyph List License", "https://spdx.org/licenses/Adobe-Glyph.html", "https://spdx.org/licenses/Adobe-Glyph.json",false, false, false),
            new SpdxLicense("GPL-2.0-with-bison-exception", "GNU General Public License v2.0 w/Bison exception", "https://spdx.org/licenses/GPL-2.0-with-bison-exception.html", "https://spdx.org/licenses/GPL-2.0-with-bison-exception.json",false, false, true),
            new SpdxLicense("MITNFA", "MIT +no-false-attribs license", "https://spdx.org/licenses/MITNFA.html", "https://spdx.org/licenses/MITNFA.json",false, false, false),
            new SpdxLicense("APSL-1.0", "Apple Public Source License 1.0", "https://spdx.org/licenses/APSL-1.0.html", "https://spdx.org/licenses/APSL-1.0.json",true, false, false),
            new SpdxLicense("JPNIC", "Japan Network Information Center License", "https://spdx.org/licenses/JPNIC.html", "https://spdx.org/licenses/JPNIC.json",false, false, false),
            new SpdxLicense("BSD-Protection", "BSD Protection License", "https://spdx.org/licenses/BSD-Protection.html", "https://spdx.org/licenses/BSD-Protection.json",false, false, false),
            new SpdxLicense("OGL-UK-1.0", "Open Government Licence v1.0", "https://spdx.org/licenses/OGL-UK-1.0.html", "https://spdx.org/licenses/OGL-UK-1.0.json",false, false, false),
            new SpdxLicense("MulanPSL-2.0", "Mulan Permissive Software License, Version 2", "https://spdx.org/licenses/MulanPSL-2.0.html", "https://spdx.org/licenses/MulanPSL-2.0.json",true, false, false),
            new SpdxLicense("ImageMagick", "ImageMagick License", "https://spdx.org/licenses/ImageMagick.html", "https://spdx.org/licenses/ImageMagick.json",false, false, false),
            new SpdxLicense("OSL-2.0", "Open Software License 2.0", "https://spdx.org/licenses/OSL-2.0.html", "https://spdx.org/licenses/OSL-2.0.json",true, true, false),
            new SpdxLicense("OLDAP-2.0", "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)", "https://spdx.org/licenses/OLDAP-2.0.html", "https://spdx.org/licenses/OLDAP-2.0.json",false, false, false),
            new SpdxLicense("bzip2-1.0.6", "bzip2 and libbzip2 License v1.0.6", "https://spdx.org/licenses/bzip2-1.0.6.html", "https://spdx.org/licenses/bzip2-1.0.6.json",false, false, false),
            new SpdxLicense("Eurosym", "Eurosym License", "https://spdx.org/licenses/Eurosym.html", "https://spdx.org/licenses/Eurosym.json",false, false, false),
            new SpdxLicense("JSON", "JSON License", "https://spdx.org/licenses/JSON.html", "https://spdx.org/licenses/JSON.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-3.0-IGO", "Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-IGO.html", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-IGO.json",false, false, false),
            new SpdxLicense("LPL-1.0", "Lucent Public License Version 1.0", "https://spdx.org/licenses/LPL-1.0.html", "https://spdx.org/licenses/LPL-1.0.json",true, false, false),
            new SpdxLicense("AGPL-1.0", "Affero General Public License v1.0", "https://spdx.org/licenses/AGPL-1.0.html", "https://spdx.org/licenses/AGPL-1.0.json",false, true, true),
            new SpdxLicense("CECILL-2.1", "CeCILL Free Software License Agreement v2.1", "https://spdx.org/licenses/CECILL-2.1.html", "https://spdx.org/licenses/CECILL-2.1.json",true, false, false),
            new SpdxLicense("MIT-0", "MIT No Attribution", "https://spdx.org/licenses/MIT-0.html", "https://spdx.org/licenses/MIT-0.json",true, false, false),
            new SpdxLicense("Spencer-99", "Spencer License 99", "https://spdx.org/licenses/Spencer-99.html", "https://spdx.org/licenses/Spencer-99.json",false, false, false),
            new SpdxLicense("PolyForm-Noncommercial-1.0.0", "PolyForm Noncommercial License 1.0.0", "https://spdx.org/licenses/PolyForm-Noncommercial-1.0.0.html", "https://spdx.org/licenses/PolyForm-Noncommercial-1.0.0.json",false, false, false),
            new SpdxLicense("Abstyles", "Abstyles License", "https://spdx.org/licenses/Abstyles.html", "https://spdx.org/licenses/Abstyles.json",false, false, false),
            new SpdxLicense("GFDL-1.3-or-later", "GNU Free Documentation License v1.3 or later", "https://spdx.org/licenses/GFDL-1.3-or-later.html", "https://spdx.org/licenses/GFDL-1.3-or-later.json",false, true, false),
            new SpdxLicense("NRL", "NRL License", "https://spdx.org/licenses/NRL.html", "https://spdx.org/licenses/NRL.json",false, false, false),
            new SpdxLicense("Libpng", "libpng License", "https://spdx.org/licenses/Libpng.html", "https://spdx.org/licenses/Libpng.json",false, false, false),
            new SpdxLicense("NAIST-2003", "Nara Institute of Science and Technology License (2003)", "https://spdx.org/licenses/NAIST-2003.html", "https://spdx.org/licenses/NAIST-2003.json",false, false, false),
            new SpdxLicense("XFree86-1.1", "XFree86 License 1.1", "https://spdx.org/licenses/XFree86-1.1.html", "https://spdx.org/licenses/XFree86-1.1.json",false, true, false),
            new SpdxLicense("OFL-1.1-RFN", "SIL Open Font License 1.1 with Reserved Font Name", "https://spdx.org/licenses/OFL-1.1-RFN.html", "https://spdx.org/licenses/OFL-1.1-RFN.json",true, false, false),
            new SpdxLicense("CC-BY-3.0-US", "Creative Commons Attribution 3.0 United States", "https://spdx.org/licenses/CC-BY-3.0-US.html", "https://spdx.org/licenses/CC-BY-3.0-US.json",false, false, false),
            new SpdxLicense("EFL-2.0", "Eiffel Forum License v2.0", "https://spdx.org/licenses/EFL-2.0.html", "https://spdx.org/licenses/EFL-2.0.json",true, true, false),
            new SpdxLicense("LPPL-1.0", "LaTeX Project Public License v1.0", "https://spdx.org/licenses/LPPL-1.0.html", "https://spdx.org/licenses/LPPL-1.0.json",false, false, false),
            new SpdxLicense("IPL-1.0", "IBM Public License v1.0", "https://spdx.org/licenses/IPL-1.0.html", "https://spdx.org/licenses/IPL-1.0.json",true, true, false),
            new SpdxLicense("ANTLR-PD", "ANTLR Software Rights Notice", "https://spdx.org/licenses/ANTLR-PD.html", "https://spdx.org/licenses/ANTLR-PD.json",false, false, false),
            new SpdxLicense("PolyForm-Small-Business-1.0.0", "PolyForm Small Business License 1.0.0", "https://spdx.org/licenses/PolyForm-Small-Business-1.0.0.html", "https://spdx.org/licenses/PolyForm-Small-Business-1.0.0.json",false, false, false),
            new SpdxLicense("GPL-1.0-only", "GNU General Public License v1.0 only", "https://spdx.org/licenses/GPL-1.0-only.html", "https://spdx.org/licenses/GPL-1.0-only.json",false, false, false),
            new SpdxLicense("CAL-1.0-Combined-Work-Exception", "Cryptographic Autonomy License 1.0 (Combined Work Exception)", "https://spdx.org/licenses/CAL-1.0-Combined-Work-Exception.html", "https://spdx.org/licenses/CAL-1.0-Combined-Work-Exception.json",true, false, false),
            new SpdxLicense("FreeImage", "FreeImage Public License v1.0", "https://spdx.org/licenses/FreeImage.html", "https://spdx.org/licenses/FreeImage.json",false, false, false),
            new SpdxLicense("GPL-2.0-with-GCC-exception", "GNU General Public License v2.0 w/GCC Runtime Library exception", "https://spdx.org/licenses/GPL-2.0-with-GCC-exception.html", "https://spdx.org/licenses/GPL-2.0-with-GCC-exception.json",false, false, true),
            new SpdxLicense("BSD-2-Clause-FreeBSD", "BSD 2-Clause FreeBSD License", "https://spdx.org/licenses/BSD-2-Clause-FreeBSD.html", "https://spdx.org/licenses/BSD-2-Clause-FreeBSD.json",false, true, true),
            new SpdxLicense("OLDAP-2.2.1", "Open LDAP Public License v2.2.1", "https://spdx.org/licenses/OLDAP-2.2.1.html", "https://spdx.org/licenses/OLDAP-2.2.1.json",false, false, false),
            new SpdxLicense("GFDL-1.2-no-invariants-or-later", "GNU Free Documentation License v1.2 or later - no invariants", "https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.json",false, false, false),
            new SpdxLicense("GFDL-1.2-no-invariants-only", "GNU Free Documentation License v1.2 only - no invariants", "https://spdx.org/licenses/GFDL-1.2-no-invariants-only.html", "https://spdx.org/licenses/GFDL-1.2-no-invariants-only.json",false, false, false),
            new SpdxLicense("Afmparse", "Afmparse License", "https://spdx.org/licenses/Afmparse.html", "https://spdx.org/licenses/Afmparse.json",false, false, false),
            new SpdxLicense("OLDAP-2.2.2", "Open LDAP Public License 2.2.2", "https://spdx.org/licenses/OLDAP-2.2.2.html", "https://spdx.org/licenses/OLDAP-2.2.2.json",false, false, false),
            new SpdxLicense("Parity-6.0.0", "The Parity Public License 6.0.0", "https://spdx.org/licenses/Parity-6.0.0.html", "https://spdx.org/licenses/Parity-6.0.0.json",false, false, false),
            new SpdxLicense("LGPL-2.1-only", "GNU Lesser General Public License v2.1 only", "https://spdx.org/licenses/LGPL-2.1-only.html", "https://spdx.org/licenses/LGPL-2.1-only.json",true, true, false),
            new SpdxLicense("MPL-1.1", "Mozilla Public License 1.1", "https://spdx.org/licenses/MPL-1.1.html", "https://spdx.org/licenses/MPL-1.1.json",true, true, false),
            new SpdxLicense("bzip2-1.0.5", "bzip2 and libbzip2 License v1.0.5", "https://spdx.org/licenses/bzip2-1.0.5.html", "https://spdx.org/licenses/bzip2-1.0.5.json",false, false, false),
            new SpdxLicense("Cube", "Cube License", "https://spdx.org/licenses/Cube.html", "https://spdx.org/licenses/Cube.json",false, false, false),
            new SpdxLicense("SISSL", "Sun Industry Standards Source License v1.1", "https://spdx.org/licenses/SISSL.html", "https://spdx.org/licenses/SISSL.json",true, true, false),
            new SpdxLicense("PostgreSQL", "PostgreSQL License", "https://spdx.org/licenses/PostgreSQL.html", "https://spdx.org/licenses/PostgreSQL.json",true, false, false),
            new SpdxLicense("CERN-OHL-P-2.0", "CERN Open Hardware Licence Version 2 - Permissive", "https://spdx.org/licenses/CERN-OHL-P-2.0.html", "https://spdx.org/licenses/CERN-OHL-P-2.0.json",true, false, false),
            new SpdxLicense("OSL-3.0", "Open Software License 3.0", "https://spdx.org/licenses/OSL-3.0.html", "https://spdx.org/licenses/OSL-3.0.json",true, true, false),
            new SpdxLicense("LPPL-1.2", "LaTeX Project Public License v1.2", "https://spdx.org/licenses/LPPL-1.2.html", "https://spdx.org/licenses/LPPL-1.2.json",false, true, false),
            new SpdxLicense("xpp", "XPP License", "https://spdx.org/licenses/xpp.html", "https://spdx.org/licenses/xpp.json",false, false, false),
            new SpdxLicense("OLDAP-2.8", "Open LDAP Public License v2.8", "https://spdx.org/licenses/OLDAP-2.8.html", "https://spdx.org/licenses/OLDAP-2.8.json",true, false, false),
            new SpdxLicense("AML", "Apple MIT License", "https://spdx.org/licenses/AML.html", "https://spdx.org/licenses/AML.json",false, false, false),
            new SpdxLicense("Motosoto", "Motosoto License", "https://spdx.org/licenses/Motosoto.html", "https://spdx.org/licenses/Motosoto.json",true, false, false),
            new SpdxLicense("Vim", "Vim License", "https://spdx.org/licenses/Vim.html", "https://spdx.org/licenses/Vim.json",false, true, false),
            new SpdxLicense("TCP-wrappers", "TCP Wrappers License", "https://spdx.org/licenses/TCP-wrappers.html", "https://spdx.org/licenses/TCP-wrappers.json",false, false, false),
            new SpdxLicense("Sendmail-8.23", "Sendmail License 8.23", "https://spdx.org/licenses/Sendmail-8.23.html", "https://spdx.org/licenses/Sendmail-8.23.json",false, false, false),
            new SpdxLicense("Ruby", "Ruby License", "https://spdx.org/licenses/Ruby.html", "https://spdx.org/licenses/Ruby.json",false, true, false),
            new SpdxLicense("GFDL-1.1-invariants-or-later", "GNU Free Documentation License v1.1 or later - invariants", "https://spdx.org/licenses/GFDL-1.1-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.1-invariants-or-later.json",false, false, false),
            new SpdxLicense("CC-BY-2.5-AU", "Creative Commons Attribution 2.5 Australia", "https://spdx.org/licenses/CC-BY-2.5-AU.html", "https://spdx.org/licenses/CC-BY-2.5-AU.json",false, false, false),
            new SpdxLicense("NetCDF", "NetCDF license", "https://spdx.org/licenses/NetCDF.html", "https://spdx.org/licenses/NetCDF.json",false, false, false),
            new SpdxLicense("BSD-1-Clause", "BSD 1-Clause License", "https://spdx.org/licenses/BSD-1-Clause.html", "https://spdx.org/licenses/BSD-1-Clause.json",true, false, false),
            new SpdxLicense("Leptonica", "Leptonica License", "https://spdx.org/licenses/Leptonica.html", "https://spdx.org/licenses/Leptonica.json",false, false, false),
            new SpdxLicense("AGPL-3.0-or-later", "GNU Affero General Public License v3.0 or later", "https://spdx.org/licenses/AGPL-3.0-or-later.html", "https://spdx.org/licenses/AGPL-3.0-or-later.json",true, true, false),
            new SpdxLicense("Beerware", "Beerware License", "https://spdx.org/licenses/Beerware.html", "https://spdx.org/licenses/Beerware.json",false, false, false),
            new SpdxLicense("EUPL-1.2", "European Union Public License 1.2", "https://spdx.org/licenses/EUPL-1.2.html", "https://spdx.org/licenses/EUPL-1.2.json",true, true, false),
            new SpdxLicense("OSET-PL-2.1", "OSET Public License version 2.1", "https://spdx.org/licenses/OSET-PL-2.1.html", "https://spdx.org/licenses/OSET-PL-2.1.json",true, false, false),
            new SpdxLicense("CC-BY-1.0", "Creative Commons Attribution 1.0 Generic", "https://spdx.org/licenses/CC-BY-1.0.html", "https://spdx.org/licenses/CC-BY-1.0.json",false, false, false),
            new SpdxLicense("SISSL-1.2", "Sun Industry Standards Source License v1.2", "https://spdx.org/licenses/SISSL-1.2.html", "https://spdx.org/licenses/SISSL-1.2.json",false, false, false),
            new SpdxLicense("CC-BY-NC-3.0", "Creative Commons Attribution Non Commercial 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-3.0.html", "https://spdx.org/licenses/CC-BY-NC-3.0.json",false, false, false),
            new SpdxLicense("GPL-2.0+", "GNU General Public License v2.0 or later", "https://spdx.org/licenses/GPL-2.0+.html", "https://spdx.org/licenses/GPL-2.0+.json",true, true, true),
            new SpdxLicense("OLDAP-1.4", "Open LDAP Public License v1.4", "https://spdx.org/licenses/OLDAP-1.4.html", "https://spdx.org/licenses/OLDAP-1.4.json",false, false, false),
            new SpdxLicense("X11", "X11 License", "https://spdx.org/licenses/X11.html", "https://spdx.org/licenses/X11.json",false, true, false),
            new SpdxLicense("Intel", "Intel Open Source License", "https://spdx.org/licenses/Intel.html", "https://spdx.org/licenses/Intel.json",true, true, false),
            new SpdxLicense("CDLA-Permissive-1.0", "Community Data License Agreement Permissive 1.0", "https://spdx.org/licenses/CDLA-Permissive-1.0.html", "https://spdx.org/licenses/CDLA-Permissive-1.0.json",false, false, false),
            new SpdxLicense("NIST-PD", "NIST Public Domain Notice", "https://spdx.org/licenses/NIST-PD.html", "https://spdx.org/licenses/NIST-PD.json",false, false, false),
            new SpdxLicense("LiLiQ-R-1.1", "Licence Libre du Québec – Réciprocité version 1.1", "https://spdx.org/licenses/LiLiQ-R-1.1.html", "https://spdx.org/licenses/LiLiQ-R-1.1.json",true, false, false),
            new SpdxLicense("SMLNJ", "Standard ML of New Jersey License", "https://spdx.org/licenses/SMLNJ.html", "https://spdx.org/licenses/SMLNJ.json",false, true, false),
            new SpdxLicense("BUSL-1.1", "Business Source License 1.1", "https://spdx.org/licenses/BUSL-1.1.html", "https://spdx.org/licenses/BUSL-1.1.json",false, false, false),
            new SpdxLicense("CDDL-1.1", "Common Development and Distribution License 1.1", "https://spdx.org/licenses/CDDL-1.1.html", "https://spdx.org/licenses/CDDL-1.1.json",false, false, false),
            new SpdxLicense("CC-BY-SA-3.0", "Creative Commons Attribution Share Alike 3.0 Unported", "https://spdx.org/licenses/CC-BY-SA-3.0.html", "https://spdx.org/licenses/CC-BY-SA-3.0.json",false, false, false),
            new SpdxLicense("CC-BY-SA-2.1-JP", "Creative Commons Attribution Share Alike 2.1 Japan", "https://spdx.org/licenses/CC-BY-SA-2.1-JP.html", "https://spdx.org/licenses/CC-BY-SA-2.1-JP.json",false, false, false),
            new SpdxLicense("Wsuipa", "Wsuipa License", "https://spdx.org/licenses/Wsuipa.html", "https://spdx.org/licenses/Wsuipa.json",false, false, false),
            new SpdxLicense("MPL-2.0-no-copyleft-exception", "Mozilla Public License 2.0 (no copyleft exception)", "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html", "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json",true, false, false),
            new SpdxLicense("Unicode-DFS-2015", "Unicode License Agreement - Data Files and Software (2015)", "https://spdx.org/licenses/Unicode-DFS-2015.html", "https://spdx.org/licenses/Unicode-DFS-2015.json",false, false, false),
            new SpdxLicense("GPL-2.0-with-classpath-exception", "GNU General Public License v2.0 w/Classpath exception", "https://spdx.org/licenses/GPL-2.0-with-classpath-exception.html", "https://spdx.org/licenses/GPL-2.0-with-classpath-exception.json",false, false, true),
            new SpdxLicense("CNRI-Python-GPL-Compatible", "CNRI Python Open Source GPL Compatible License Agreement", "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html", "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.json",false, false, false),
            new SpdxLicense("OLDAP-2.0.1", "Open LDAP Public License v2.0.1", "https://spdx.org/licenses/OLDAP-2.0.1.html", "https://spdx.org/licenses/OLDAP-2.0.1.json",false, false, false),
            new SpdxLicense("psutils", "psutils License", "https://spdx.org/licenses/psutils.html", "https://spdx.org/licenses/psutils.json",false, false, false),
            new SpdxLicense("eCos-2.0", "eCos license version 2.0", "https://spdx.org/licenses/eCos-2.0.html", "https://spdx.org/licenses/eCos-2.0.json",false, true, true),
            new SpdxLicense("CC-BY-2.0", "Creative Commons Attribution 2.0 Generic", "https://spdx.org/licenses/CC-BY-2.0.html", "https://spdx.org/licenses/CC-BY-2.0.json",false, false, false),
            new SpdxLicense("Artistic-2.0", "Artistic License 2.0", "https://spdx.org/licenses/Artistic-2.0.html", "https://spdx.org/licenses/Artistic-2.0.json",true, true, false),
            new SpdxLicense("Artistic-1.0-cl8", "Artistic License 1.0 w/clause 8", "https://spdx.org/licenses/Artistic-1.0-cl8.html", "https://spdx.org/licenses/Artistic-1.0-cl8.json",true, false, false),
            new SpdxLicense("Aladdin", "Aladdin Free Public License", "https://spdx.org/licenses/Aladdin.html", "https://spdx.org/licenses/Aladdin.json",false, false, false),
            new SpdxLicense("LGPL-3.0-or-later", "GNU Lesser General Public License v3.0 or later", "https://spdx.org/licenses/LGPL-3.0-or-later.html", "https://spdx.org/licenses/LGPL-3.0-or-later.json",true, true, false),
            new SpdxLicense("SNIA", "SNIA Public License 1.1", "https://spdx.org/licenses/SNIA.html", "https://spdx.org/licenses/SNIA.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-3.0-IGO", "Creative Commons Attribution Non Commercial Share Alike 3.0 IGO", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-IGO.html", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-IGO.json",false, false, false),
            new SpdxLicense("AGPL-3.0", "GNU Affero General Public License v3.0", "https://spdx.org/licenses/AGPL-3.0.html", "https://spdx.org/licenses/AGPL-3.0.json",true, true, true),
            new SpdxLicense("SSPL-1.0", "Server Side Public License, v 1", "https://spdx.org/licenses/SSPL-1.0.html", "https://spdx.org/licenses/SSPL-1.0.json",false, false, false),
            new SpdxLicense("RPSL-1.0", "RealNetworks Public Source License v1.0", "https://spdx.org/licenses/RPSL-1.0.html", "https://spdx.org/licenses/RPSL-1.0.json",true, true, false),
            new SpdxLicense("MIT-open-group", "MIT Open Group variant", "https://spdx.org/licenses/MIT-open-group.html", "https://spdx.org/licenses/MIT-open-group.json",false, false, false),
            new SpdxLicense("BSD-3-Clause-LBNL", "Lawrence Berkeley National Labs BSD variant license", "https://spdx.org/licenses/BSD-3-Clause-LBNL.html", "https://spdx.org/licenses/BSD-3-Clause-LBNL.json",true, false, false),
            new SpdxLicense("GPL-1.0", "GNU General Public License v1.0 only", "https://spdx.org/licenses/GPL-1.0.html", "https://spdx.org/licenses/GPL-1.0.json",false, false, true),
            new SpdxLicense("CECILL-B", "CeCILL-B Free Software License Agreement", "https://spdx.org/licenses/CECILL-B.html", "https://spdx.org/licenses/CECILL-B.json",false, true, false),
            new SpdxLicense("Frameworx-1.0", "Frameworx Open License 1.0", "https://spdx.org/licenses/Frameworx-1.0.html", "https://spdx.org/licenses/Frameworx-1.0.json",true, false, false),
            new SpdxLicense("RHeCos-1.1", "Red Hat eCos Public License v1.1", "https://spdx.org/licenses/RHeCos-1.1.html", "https://spdx.org/licenses/RHeCos-1.1.json",false, false, false),
            new SpdxLicense("LAL-1.2", "Licence Art Libre 1.2", "https://spdx.org/licenses/LAL-1.2.html", "https://spdx.org/licenses/LAL-1.2.json",false, false, false),
            new SpdxLicense("OML", "Open Market License", "https://spdx.org/licenses/OML.html", "https://spdx.org/licenses/OML.json",false, false, false),
            new SpdxLicense("UCL-1.0", "Upstream Compatibility License v1.0", "https://spdx.org/licenses/UCL-1.0.html", "https://spdx.org/licenses/UCL-1.0.json",true, false, false),
            new SpdxLicense("GPL-2.0-with-autoconf-exception", "GNU General Public License v2.0 w/Autoconf exception", "https://spdx.org/licenses/GPL-2.0-with-autoconf-exception.html", "https://spdx.org/licenses/GPL-2.0-with-autoconf-exception.json",false, false, true),
            new SpdxLicense("APL-1.0", "Adaptive Public License 1.0", "https://spdx.org/licenses/APL-1.0.html", "https://spdx.org/licenses/APL-1.0.json",true, false, false),
            new SpdxLicense("OLDAP-2.2", "Open LDAP Public License v2.2", "https://spdx.org/licenses/OLDAP-2.2.html", "https://spdx.org/licenses/OLDAP-2.2.json",false, false, false),
            new SpdxLicense("CERN-OHL-W-2.0", "CERN Open Hardware Licence Version 2 - Weakly Reciprocal", "https://spdx.org/licenses/CERN-OHL-W-2.0.html", "https://spdx.org/licenses/CERN-OHL-W-2.0.json",true, false, false),
            new SpdxLicense("DRL-1.0", "Detection Rule License 1.0", "https://spdx.org/licenses/DRL-1.0.html", "https://spdx.org/licenses/DRL-1.0.json",false, false, false),
            new SpdxLicense("GPL-3.0+", "GNU General Public License v3.0 or later", "https://spdx.org/licenses/GPL-3.0+.html", "https://spdx.org/licenses/GPL-3.0+.json",true, true, true),
            new SpdxLicense("CC-BY-ND-1.0", "Creative Commons Attribution No Derivatives 1.0 Generic", "https://spdx.org/licenses/CC-BY-ND-1.0.html", "https://spdx.org/licenses/CC-BY-ND-1.0.json",false, false, false),
            new SpdxLicense("GFDL-1.3-no-invariants-or-later", "GNU Free Documentation License v1.3 or later - no invariants", "https://spdx.org/licenses/GFDL-1.3-no-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.3-no-invariants-or-later.json",false, false, false),
            new SpdxLicense("CECILL-1.1", "CeCILL Free Software License Agreement v1.1", "https://spdx.org/licenses/CECILL-1.1.html", "https://spdx.org/licenses/CECILL-1.1.json",false, false, false),
            new SpdxLicense("Noweb", "Noweb License", "https://spdx.org/licenses/Noweb.html", "https://spdx.org/licenses/Noweb.json",false, false, false),
            new SpdxLicense("MakeIndex", "MakeIndex License", "https://spdx.org/licenses/MakeIndex.html", "https://spdx.org/licenses/MakeIndex.json",false, false, false),
            new SpdxLicense("MS-RL", "Microsoft Reciprocal License", "https://spdx.org/licenses/MS-RL.html", "https://spdx.org/licenses/MS-RL.json",true, true, false),
            new SpdxLicense("TORQUE-1.1", "TORQUE v2.5+ Software License v1.1", "https://spdx.org/licenses/TORQUE-1.1.html", "https://spdx.org/licenses/TORQUE-1.1.json",false, false, false),
            new SpdxLicense("AFL-3.0", "Academic Free License v3.0", "https://spdx.org/licenses/AFL-3.0.html", "https://spdx.org/licenses/AFL-3.0.json",true, true, false),
            new SpdxLicense("GFDL-1.1-invariants-only", "GNU Free Documentation License v1.1 only - invariants", "https://spdx.org/licenses/GFDL-1.1-invariants-only.html", "https://spdx.org/licenses/GFDL-1.1-invariants-only.json",false, false, false),
            new SpdxLicense("GFDL-1.1", "GNU Free Documentation License v1.1", "https://spdx.org/licenses/GFDL-1.1.html", "https://spdx.org/licenses/GFDL-1.1.json",false, true, true),
            new SpdxLicense("FTL", "Freetype Project License", "https://spdx.org/licenses/FTL.html", "https://spdx.org/licenses/FTL.json",false, true, false),
            new SpdxLicense("AFL-2.0", "Academic Free License v2.0", "https://spdx.org/licenses/AFL-2.0.html", "https://spdx.org/licenses/AFL-2.0.json",true, true, false),
            new SpdxLicense("GPL-3.0-with-autoconf-exception", "GNU General Public License v3.0 w/Autoconf exception", "https://spdx.org/licenses/GPL-3.0-with-autoconf-exception.html", "https://spdx.org/licenses/GPL-3.0-with-autoconf-exception.json",false, false, true),
            new SpdxLicense("LPPL-1.3a", "LaTeX Project Public License v1.3a", "https://spdx.org/licenses/LPPL-1.3a.html", "https://spdx.org/licenses/LPPL-1.3a.json",false, true, false),
            new SpdxLicense("OLDAP-1.2", "Open LDAP Public License v1.2", "https://spdx.org/licenses/OLDAP-1.2.html", "https://spdx.org/licenses/OLDAP-1.2.json",false, false, false),
            new SpdxLicense("ODbL-1.0", "Open Data Commons Open Database License v1.0", "https://spdx.org/licenses/ODbL-1.0.html", "https://spdx.org/licenses/ODbL-1.0.json",false, true, false),
            new SpdxLicense("LiLiQ-Rplus-1.1", "Licence Libre du Québec – Réciprocité forte version 1.1", "https://spdx.org/licenses/LiLiQ-Rplus-1.1.html", "https://spdx.org/licenses/LiLiQ-Rplus-1.1.json",true, false, false),
            new SpdxLicense("Qhull", "Qhull License", "https://spdx.org/licenses/Qhull.html", "https://spdx.org/licenses/Qhull.json",false, false, false),
            new SpdxLicense("OCCT-PL", "Open CASCADE Technology Public License", "https://spdx.org/licenses/OCCT-PL.html", "https://spdx.org/licenses/OCCT-PL.json",false, false, false),
            new SpdxLicense("NTP", "NTP License", "https://spdx.org/licenses/NTP.html", "https://spdx.org/licenses/NTP.json",true, false, false),
            new SpdxLicense("EUPL-1.1", "European Union Public License 1.1", "https://spdx.org/licenses/EUPL-1.1.html", "https://spdx.org/licenses/EUPL-1.1.json",true, true, false),
            new SpdxLicense("CPOL-1.02", "Code Project Open License 1.02", "https://spdx.org/licenses/CPOL-1.02.html", "https://spdx.org/licenses/CPOL-1.02.json",false, false, false),
            new SpdxLicense("OCLC-2.0", "OCLC Research Public License 2.0", "https://spdx.org/licenses/OCLC-2.0.html", "https://spdx.org/licenses/OCLC-2.0.json",true, false, false),
            new SpdxLicense("OLDAP-2.1", "Open LDAP Public License v2.1", "https://spdx.org/licenses/OLDAP-2.1.html", "https://spdx.org/licenses/OLDAP-2.1.json",false, false, false),
            new SpdxLicense("Intel-ACPI", "Intel ACPI Software License Agreement", "https://spdx.org/licenses/Intel-ACPI.html", "https://spdx.org/licenses/Intel-ACPI.json",false, false, false),
            new SpdxLicense("OFL-1.0-RFN", "SIL Open Font License 1.0 with Reserved Font Name", "https://spdx.org/licenses/OFL-1.0-RFN.html", "https://spdx.org/licenses/OFL-1.0-RFN.json",false, false, false),
            new SpdxLicense("CC0-1.0", "Creative Commons Zero v1.0 Universal", "https://spdx.org/licenses/CC0-1.0.html", "https://spdx.org/licenses/CC0-1.0.json",false, true, false),
            new SpdxLicense("LGPL-2.0-or-later", "GNU Library General Public License v2 or later", "https://spdx.org/licenses/LGPL-2.0-or-later.html", "https://spdx.org/licenses/LGPL-2.0-or-later.json",true, false, false),
            new SpdxLicense("SGI-B-1.1", "SGI Free Software License B v1.1", "https://spdx.org/licenses/SGI-B-1.1.html", "https://spdx.org/licenses/SGI-B-1.1.json",false, false, false),
            new SpdxLicense("CC-BY-NC-ND-3.0", "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-ND-3.0.html", "https://spdx.org/licenses/CC-BY-NC-ND-3.0.json",false, false, false),
            new SpdxLicense("etalab-2.0", "Etalab Open License 2.0", "https://spdx.org/licenses/etalab-2.0.html", "https://spdx.org/licenses/etalab-2.0.json",false, false, false),
            new SpdxLicense("CC-BY-NC-SA-2.0-FR", "Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-FR.html", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-FR.json",false, false, false),
            new SpdxLicense("GPL-3.0-only", "GNU General Public License v3.0 only", "https://spdx.org/licenses/GPL-3.0-only.html", "https://spdx.org/licenses/GPL-3.0-only.json",true, true, false),
            new SpdxLicense("Zend-2.0", "Zend License v2.0", "https://spdx.org/licenses/Zend-2.0.html", "https://spdx.org/licenses/Zend-2.0.json",false, true, false),
            new SpdxLicense("MirOS", "The MirOS Licence", "https://spdx.org/licenses/MirOS.html", "https://spdx.org/licenses/MirOS.json",true, false, false),
            new SpdxLicense("BSD-3-Clause-No-Nuclear-License-2014", "BSD 3-Clause No Nuclear License 2014", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json",false, false, false),
            new SpdxLicense("BitTorrent-1.0", "BitTorrent Open Source License v1.0", "https://spdx.org/licenses/BitTorrent-1.0.html", "https://spdx.org/licenses/BitTorrent-1.0.json",false, false, false),
            new SpdxLicense("CC-BY-ND-3.0", "Creative Commons Attribution No Derivatives 3.0 Unported", "https://spdx.org/licenses/CC-BY-ND-3.0.html", "https://spdx.org/licenses/CC-BY-ND-3.0.json",false, false, false),
            new SpdxLicense("MIT", "MIT License", "https://spdx.org/licenses/MIT.html", "https://spdx.org/licenses/MIT.json",true, true, false),
            new SpdxLicense("NIST-PD-fallback", "NIST Public Domain Notice with license fallback", "https://spdx.org/licenses/NIST-PD-fallback.html", "https://spdx.org/licenses/NIST-PD-fallback.json",false, false, false),
            new SpdxLicense("CC-BY-NC-3.0-DE", "Creative Commons Attribution Non Commercial 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-3.0-DE.html", "https://spdx.org/licenses/CC-BY-NC-3.0-DE.json",false, false, false),
            new SpdxLicense("FSFULLR", "FSF Unlimited License (with License Retention)", "https://spdx.org/licenses/FSFULLR.html", "https://spdx.org/licenses/FSFULLR.json",false, false, false),
            new SpdxLicense("CC-BY-NC-1.0", "Creative Commons Attribution Non Commercial 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-1.0.html", "https://spdx.org/licenses/CC-BY-NC-1.0.json",false, false, false),
            new SpdxLicense("Python-2.0", "Python License 2.0", "https://spdx.org/licenses/Python-2.0.html", "https://spdx.org/licenses/Python-2.0.json",true, true, false),
            new SpdxLicense("ANTLR-PD-fallback", "ANTLR Software Rights Notice with license fallback", "https://spdx.org/licenses/ANTLR-PD-fallback.html", "https://spdx.org/licenses/ANTLR-PD-fallback.json",false, false, false),
            new SpdxLicense("MulanPSL-1.0", "Mulan Permissive Software License, Version 1", "https://spdx.org/licenses/MulanPSL-1.0.html", "https://spdx.org/licenses/MulanPSL-1.0.json",false, false, false),
            new SpdxLicense("wxWindows", "wxWindows Library License", "https://spdx.org/licenses/wxWindows.html", "https://spdx.org/licenses/wxWindows.json",true, false, true),
            new SpdxLicense("CC-BY-4.0", "Creative Commons Attribution 4.0 International", "https://spdx.org/licenses/CC-BY-4.0.html", "https://spdx.org/licenses/CC-BY-4.0.json",false, true, false),
            new SpdxLicense("Rdisc", "Rdisc License", "https://spdx.org/licenses/Rdisc.html", "https://spdx.org/licenses/Rdisc.json",false, false, false),
            new SpdxLicense("MIT-enna", "enna License", "https://spdx.org/licenses/MIT-enna.html", "https://spdx.org/licenses/MIT-enna.json",false, false, false),
            new SpdxLicense("BSD-4-Clause-UC", "BSD-4-Clause (University of California-Specific)", "https://spdx.org/licenses/BSD-4-Clause-UC.html", "https://spdx.org/licenses/BSD-4-Clause-UC.json",false, false, false),
            new SpdxLicense("MPL-2.0", "Mozilla Public License 2.0", "https://spdx.org/licenses/MPL-2.0.html", "https://spdx.org/licenses/MPL-2.0.json",true, true, false),
            new SpdxLicense("YPL-1.0", "Yahoo! Public License v1.0", "https://spdx.org/licenses/YPL-1.0.html", "https://spdx.org/licenses/YPL-1.0.json",false, false, false),
            new SpdxLicense("ZPL-2.0", "Zope Public License 2.0", "https://spdx.org/licenses/ZPL-2.0.html", "https://spdx.org/licenses/ZPL-2.0.json",true, true, false),
            new SpdxLicense("copyleft-next-0.3.1", "copyleft-next 0.3.1", "https://spdx.org/licenses/copyleft-next-0.3.1.html", "https://spdx.org/licenses/copyleft-next-0.3.1.json",false, false, false),
            new SpdxLicense("GFDL-1.3-invariants-or-later", "GNU Free Documentation License v1.3 or later - invariants", "https://spdx.org/licenses/GFDL-1.3-invariants-or-later.html", "https://spdx.org/licenses/GFDL-1.3-invariants-or-later.json",false, false, false),
            new SpdxLicense("LPL-1.02", "Lucent Public License v1.02", "https://spdx.org/licenses/LPL-1.02.html", "https://spdx.org/licenses/LPL-1.02.json",true, true, false),
            new SpdxLicense("NLOD-1.0", "Norwegian Licence for Open Government Data (NLOD) 1.0", "https://spdx.org/licenses/NLOD-1.0.html", "https://spdx.org/licenses/NLOD-1.0.json",false, false, false),
            new SpdxLicense("MIT-Modern-Variant", "MIT License Modern Variant", "https://spdx.org/licenses/MIT-Modern-Variant.html", "https://spdx.org/licenses/MIT-Modern-Variant.json",true, false, false),
            new SpdxLicense("MTLL", "Matrix Template Library License", "https://spdx.org/licenses/MTLL.html", "https://spdx.org/licenses/MTLL.json",false, false, false),
            new SpdxLicense("ECL-1.0", "Educational Community License v1.0", "https://spdx.org/licenses/ECL-1.0.html", "https://spdx.org/licenses/ECL-1.0.json",true, false, false),
            new SpdxLicense("EPICS", "EPICS Open License", "https://spdx.org/licenses/EPICS.html", "https://spdx.org/licenses/EPICS.json",false, false, false),
            new SpdxLicense("BSD-3-Clause-Attribution", "BSD with attribution", "https://spdx.org/licenses/BSD-3-Clause-Attribution.html", "https://spdx.org/licenses/BSD-3-Clause-Attribution.json",false, false, false),
            new SpdxLicense("GFDL-1.2-invariants-only", "GNU Free Documentation License v1.2 only - invariants", "https://spdx.org/licenses/GFDL-1.2-invariants-only.html", "https://spdx.org/licenses/GFDL-1.2-invariants-only.json",false, false, false),
            new SpdxLicense("AMDPLPA", "AMD's plpa_map.c License", "https://spdx.org/licenses/AMDPLPA.html", "https://spdx.org/licenses/AMDPLPA.json",false, false, false),
            new SpdxLicense("FSFUL", "FSF Unlimited License", "https://spdx.org/licenses/FSFUL.html", "https://spdx.org/licenses/FSFUL.json",false, false, false),
            new SpdxLicense("CC-BY-3.0-AT", "Creative Commons Attribution 3.0 Austria", "https://spdx.org/licenses/CC-BY-3.0-AT.html", "https://spdx.org/licenses/CC-BY-3.0-AT.json",false, false, false),
            new SpdxLicense("CDLA-Sharing-1.0", "Community Data License Agreement Sharing 1.0", "https://spdx.org/licenses/CDLA-Sharing-1.0.html", "https://spdx.org/licenses/CDLA-Sharing-1.0.json",false, false, false),
            new SpdxLicense("OLDAP-2.6", "Open LDAP Public License v2.6", "https://spdx.org/licenses/OLDAP-2.6.html", "https://spdx.org/licenses/OLDAP-2.6.json",false, false, false),
            new SpdxLicense("LAL-1.3", "Licence Art Libre 1.3", "https://spdx.org/licenses/LAL-1.3.html", "https://spdx.org/licenses/LAL-1.3.json",false, false, false),
            new SpdxLicense("OPUBL-1.0", "Open Publication License v1.0", "https://spdx.org/licenses/OPUBL-1.0.html", "https://spdx.org/licenses/OPUBL-1.0.json",false, false, false),
            new SpdxLicense("Bahyph", "Bahyph License", "https://spdx.org/licenses/Bahyph.html", "https://spdx.org/licenses/Bahyph.json",false, false, false),
            new SpdxLicense("CC-BY-SA-3.0-AT", "Creative Commons Attribution Share Alike 3.0 Austria", "https://spdx.org/licenses/CC-BY-SA-3.0-AT.html", "https://spdx.org/licenses/CC-BY-SA-3.0-AT.json",false, false, false),
            new SpdxLicense("AFL-2.1", "Academic Free License v2.1", "https://spdx.org/licenses/AFL-2.1.html", "https://spdx.org/licenses/AFL-2.1.json",true, true, false),
            new SpdxLicense("NTP-0", "NTP No Attribution", "https://spdx.org/licenses/NTP-0.html", "https://spdx.org/licenses/NTP-0.json",false, false, false),
            new SpdxLicense("OSL-2.1", "Open Software License 2.1", "https://spdx.org/licenses/OSL-2.1.html", "https://spdx.org/licenses/OSL-2.1.json",true, true, false),
            new SpdxLicense("LGPL-2.0", "GNU Library General Public License v2 only", "https://spdx.org/licenses/LGPL-2.0.html", "https://spdx.org/licenses/LGPL-2.0.json",true, false, true),
            new SpdxLicense("NCGL-UK-2.0", "Non-Commercial Government Licence", "https://spdx.org/licenses/NCGL-UK-2.0.html", "https://spdx.org/licenses/NCGL-UK-2.0.json",false, false, false),
            new SpdxLicense("Glulxe", "Glulxe License", "https://spdx.org/licenses/Glulxe.html", "https://spdx.org/licenses/Glulxe.json",false, false, false),
            new SpdxLicense("copyleft-next-0.3.0", "copyleft-next 0.3.0", "https://spdx.org/licenses/copyleft-next-0.3.0.html", "https://spdx.org/licenses/copyleft-next-0.3.0.json",false, false, false),
            new SpdxLicense("dvipdfm", "dvipdfm License", "https://spdx.org/licenses/dvipdfm.html", "https://spdx.org/licenses/dvipdfm.json",false, false, false),
            new SpdxLicense("libtiff", "libtiff License", "https://spdx.org/licenses/libtiff.html", "https://spdx.org/licenses/libtiff.json",false, false, false),
            new SpdxLicense("GLWTPL", "Good Luck With That Public License", "https://spdx.org/licenses/GLWTPL.html", "https://spdx.org/licenses/GLWTPL.json",false, false, false),
            new SpdxLicense("StandardML-NJ", "Standard ML of New Jersey License", "https://spdx.org/licenses/StandardML-NJ.html", "https://spdx.org/licenses/StandardML-NJ.json",false, true, true),
            new SpdxLicense("CAL-1.0", "Cryptographic Autonomy License 1.0", "https://spdx.org/licenses/CAL-1.0.html", "https://spdx.org/licenses/CAL-1.0.json",true, false, false),
            new SpdxLicense("Artistic-1.0-Perl", "Artistic License 1.0 (Perl)", "https://spdx.org/licenses/Artistic-1.0-Perl.html", "https://spdx.org/licenses/Artistic-1.0-Perl.json",true, false, false),
            new SpdxLicense("gSOAP-1.3b", "gSOAP Public License v1.3b", "https://spdx.org/licenses/gSOAP-1.3b.html", "https://spdx.org/licenses/gSOAP-1.3b.json",false, false, false),
            new SpdxLicense("OLDAP-2.5", "Open LDAP Public License v2.5", "https://spdx.org/licenses/OLDAP-2.5.html", "https://spdx.org/licenses/OLDAP-2.5.json",false, false, false),
            new SpdxLicense("Interbase-1.0", "Interbase Public License v1.0", "https://spdx.org/licenses/Interbase-1.0.html", "https://spdx.org/licenses/Interbase-1.0.json",false, false, false),
            new SpdxLicense("LGPL-2.1", "GNU Lesser General Public License v2.1 only", "https://spdx.org/licenses/LGPL-2.1.html", "https://spdx.org/licenses/LGPL-2.1.json",true, true, true),
            new SpdxLicense("MS-PL", "Microsoft Public License", "https://spdx.org/licenses/MS-PL.html", "https://spdx.org/licenses/MS-PL.json",true, true, false),
        };
    }
}
